// 参数名和文本描述的映射关系
export const ParamsMap = {
    browser_type: '浏览器类型',
    open_url: '网页地址',
    tag: '页面标签名',
    index: '顺序索引',
    title: '网页标题',
    url: '网页URL',
    height: '滚动到指定高度',
    script: 'JS脚本(箭头函数)',
    args: "传给JS的参数",
    locator: "元素定位表达式",
    value: "值",
    timeout: '超时时间(毫秒)',
    button: "按键:left | right",
    count: "次数",
    x: 'X坐标',
    y: 'Y坐标',
    delay: "时长(秒)",
    key: "按键",
    start_selector: "启始元素定位",
    end_selector: "结束元素定位",
    frame: "iframe定位表达式",
    expect_results: "预期结果",
    is_equal: "是否相等",
    attr_name: "属性名称",
    wait_until:"等待状态"
}